//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTool.ChinaStock {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="ChinaStock.ChinaStockWebServiceSoap")]
    public interface ChinaStockWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStockImageByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getStockImageByCode(string theStockCode);
        
        // CODEGEN: Parameter 'getStockImageByteByCodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStockImageByteByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockTool.ChinaStock.getStockImageByteByCodeResponse getStockImageByteByCode(StockTool.ChinaStock.getStockImageByteByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStockImage_kByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void getStockImage_kByCode(string theStockCode, string theType);
        
        // CODEGEN: Parameter 'getStockImage_kByteByCodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStockImage_kByteByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StockTool.ChinaStock.getStockImage_kByteByCodeResponse getStockImage_kByteByCode(StockTool.ChinaStock.getStockImage_kByteByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getStockInfoByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getStockInfoByCode(string theStockCode);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockImageByteByCode", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class getStockImageByteByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string theStockCode;
        
        public getStockImageByteByCodeRequest() {
        }
        
        public getStockImageByteByCodeRequest(string theStockCode) {
            this.theStockCode = theStockCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockImageByteByCodeResponse", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class getStockImageByteByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getStockImageByteByCodeResult;
        
        public getStockImageByteByCodeResponse() {
        }
        
        public getStockImageByteByCodeResponse(byte[] getStockImageByteByCodeResult) {
            this.getStockImageByteByCodeResult = getStockImageByteByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockImage_kByteByCode", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class getStockImage_kByteByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        public string theStockCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=1)]
        public string theType;
        
        public getStockImage_kByteByCodeRequest() {
        }
        
        public getStockImage_kByteByCodeRequest(string theStockCode, string theType) {
            this.theStockCode = theStockCode;
            this.theType = theType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockImage_kByteByCodeResponse", WrapperNamespace="http://WebXml.com.cn/", IsWrapped=true)]
    public partial class getStockImage_kByteByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebXml.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getStockImage_kByteByCodeResult;
        
        public getStockImage_kByteByCodeResponse() {
        }
        
        public getStockImage_kByteByCodeResponse(byte[] getStockImage_kByteByCodeResult) {
            this.getStockImage_kByteByCodeResult = getStockImage_kByteByCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChinaStockWebServiceSoapChannel : StockTool.ChinaStock.ChinaStockWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChinaStockWebServiceSoapClient : System.ServiceModel.ClientBase<StockTool.ChinaStock.ChinaStockWebServiceSoap>, StockTool.ChinaStock.ChinaStockWebServiceSoap {
        
        public ChinaStockWebServiceSoapClient() {
        }
        
        public ChinaStockWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChinaStockWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaStockWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChinaStockWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void getStockImageByCode(string theStockCode) {
            base.Channel.getStockImageByCode(theStockCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockTool.ChinaStock.getStockImageByteByCodeResponse StockTool.ChinaStock.ChinaStockWebServiceSoap.getStockImageByteByCode(StockTool.ChinaStock.getStockImageByteByCodeRequest request) {
            return base.Channel.getStockImageByteByCode(request);
        }
        
        public byte[] getStockImageByteByCode(string theStockCode) {
            StockTool.ChinaStock.getStockImageByteByCodeRequest inValue = new StockTool.ChinaStock.getStockImageByteByCodeRequest();
            inValue.theStockCode = theStockCode;
            StockTool.ChinaStock.getStockImageByteByCodeResponse retVal = ((StockTool.ChinaStock.ChinaStockWebServiceSoap)(this)).getStockImageByteByCode(inValue);
            return retVal.getStockImageByteByCodeResult;
        }
        
        public void getStockImage_kByCode(string theStockCode, string theType) {
            base.Channel.getStockImage_kByCode(theStockCode, theType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockTool.ChinaStock.getStockImage_kByteByCodeResponse StockTool.ChinaStock.ChinaStockWebServiceSoap.getStockImage_kByteByCode(StockTool.ChinaStock.getStockImage_kByteByCodeRequest request) {
            return base.Channel.getStockImage_kByteByCode(request);
        }
        
        public byte[] getStockImage_kByteByCode(string theStockCode, string theType) {
            StockTool.ChinaStock.getStockImage_kByteByCodeRequest inValue = new StockTool.ChinaStock.getStockImage_kByteByCodeRequest();
            inValue.theStockCode = theStockCode;
            inValue.theType = theType;
            StockTool.ChinaStock.getStockImage_kByteByCodeResponse retVal = ((StockTool.ChinaStock.ChinaStockWebServiceSoap)(this)).getStockImage_kByteByCode(inValue);
            return retVal.getStockImage_kByteByCodeResult;
        }
        
        public string[] getStockInfoByCode(string theStockCode) {
            return base.Channel.getStockInfoByCode(theStockCode);
        }
    }
}
