//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Id { get; set; }
        public string AdName { get; set; }
        public string Code { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int AdType { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int WebsiteId { get; set; }
    
        public virtual Website Website { get; set; }
    }
}
