//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Website
    {
        public int ID { get; set; }
        public int ArticleId { get; set; }
        public int WebsiteId { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Website Website { get; set; }
    }
}
