//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseRoleAction
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual BaseAction BaseAction { get; set; }
        public virtual BaseRole BaseRole { get; set; }
    }
}
