//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUser
    {
        public BaseUser()
        {
            this.BaseUserRole = new HashSet<BaseUserRole>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<BaseUserRole> BaseUserRole { get; set; }
    }
}
