//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Article = new HashSet<Article>();
            this.KeyWord = new HashSet<KeyWord>();
            this.SpiderContent = new HashSet<SpiderContent>();
            this.SpiderLink = new HashSet<SpiderLink>();
            this.Website_Category = new HashSet<Website_Category>();
        }
    
        public int Id { get; set; }
        public string CateName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<KeyWord> KeyWord { get; set; }
        public virtual ICollection<SpiderContent> SpiderContent { get; set; }
        public virtual ICollection<SpiderLink> SpiderLink { get; set; }
        public virtual ICollection<Website_Category> Website_Category { get; set; }
    }
}
