//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DataCenterDB : DbContext
    {
        public DataCenterDB(string ConnectionNameOrConnectionString)
            : base(ConnectionNameOrConnectionString)
        {
        }

        protected DataCenterDB(DbConnection dbConnection)
            : base(dbConnection, true)
        {
        }

        

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual void Commit()
        {
            base.SaveChanges();
        }
        public DbSet<Advertisement> Advertisement { get; set; }
        public DbSet<Article> Article { get; set; }
        public DbSet<Article_Website> Article_Website { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<KeyWord> KeyWord { get; set; }
        public DbSet<SpiderContent> SpiderContent { get; set; }
        public DbSet<SpiderLink> SpiderLink { get; set; }
        public DbSet<Website> Website { get; set; }
        public DbSet<Website_Category> Website_Category { get; set; }
        public DbSet<WebsiteSetting> WebsiteSetting { get; set; }
        public DbSet<BaseAction> BaseAction { get; set; }
        public DbSet<BaseRole> BaseRole { get; set; }
        public DbSet<BaseRoleAction> BaseRoleAction { get; set; }
        public DbSet<BaseUser> BaseUser { get; set; }
        public DbSet<BaseUserRole> BaseUserRole { get; set; }
    }
}
