//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWord
    {
        public int Id { get; set; }
        public string KeyWord1 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsCatched { get; set; }
        public bool IsExpired { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
