//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Category
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int WebsiteId { get; set; }
        public string MappingName { get; set; }
        public bool IspuPlished { get; set; }
        public int OrderNum { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Website Website { get; set; }
    }
}
