//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public Website()
        {
            this.Advertisement = new HashSet<Advertisement>();
            this.Article_Website = new HashSet<Article_Website>();
            this.Comment = new HashSet<Comment>();
            this.Website_Category = new HashSet<Website_Category>();
            this.WebsiteSetting = new HashSet<WebsiteSetting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SiteNameCn { get; set; }
        public string SiteNameEn { get; set; }
        public string SiteUrl { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ICollection<Advertisement> Advertisement { get; set; }
        public virtual ICollection<Article_Website> Article_Website { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Website_Category> Website_Category { get; set; }
        public virtual ICollection<WebsiteSetting> WebsiteSetting { get; set; }
    }
}
