document.writeln("<div class=\"rts\">");
document.writeln("	    <dl class=\"help\">");
document.writeln("		    <dt><strong>新手上路<\/strong><\/dt>");
document.writeln("			<dd>");
document.writeln("					<li><a href=\"http:\/\/member1.taobao.com\/member\/newbie.htm\" target=\"_blank\" rel=\"nofollow\">免费注册<\/a><\/li>");
document.writeln("					<li><a href=\"https:\/\/lab.alipay.com\/user\/reg\/index.htm\" target=\"_blank\" rel=\"nofollow\">开通支付宝<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/service.taobao.com\/support\/9932-9934-9941\/9941.htm\" target=\"_blank\" rel=\"nofollow\">支付宝充值<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/service.taobao.com\/support\/knowledge-1115818.htm\" target=\"_blank\" rel=\"nofollow\">如何购买<\/a><\/li>");
document.writeln("			<\/dd>");
document.writeln("		<\/dl>");
document.writeln("		<dl class=\"help\">");
document.writeln("		    <dt><strong>支付方式<\/strong><\/dt>");
document.writeln("			<dd>");
document.writeln("					<li><a href=\"http:\/\/abc.alipay.com\/school\/express.htm\" target=\"_blank\" rel=\"nofollow\">快捷支付<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/abc.alipay.com\/school\/remainpay.html\" target=\"_blank\" rel=\"nofollow\">余额支付<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/abc.alipay.com\/school\/codpay.html\" target=\"_blank\" rel=\"nofollow\">货到付款<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/abc.alipay.com\/school\/bankonline.html\" target=\"_blank\" rel=\"nofollow\">网上银行支付<\/a><\/li>");
document.writeln("			<\/dd>");
document.writeln("		<\/dl>");
document.writeln("		<dl class=\"help\">");
document.writeln("		    <dt><strong>售后服务<\/strong><\/dt>");
document.writeln("			<dd>");
document.writeln("					<li><a href=\"http:\/\/service.taobao.com\/support\/9799.htm\" target=\"_blank\" rel=\"nofollow\">交易维权<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/service.taobao.com\/support\/9801.htm\" target=\"_blank\" rel=\"nofollow\">投诉卖家流程<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/service.taobao.com\/support\/9802.htm\" target=\"_blank\" rel=\"nofollow\">举报卖家流程<\/a><\/li>");
document.writeln("					<li><a href=\"http:\/\/www.taobao.com\/about\/contact.php\" target=\"_blank\" rel=\"nofollow\">淘宝客服电话<\/a><\/li>");
document.writeln("			<\/dd>");
document.writeln("		<\/dl>");
document.writeln("	<\/div>")